kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node:16
  commands:
    - npm install

- name: test
  image: node:16
  commands:
    - npm test

- name: build
  image: node:16
  commands:
    - npm run build

- name: publish 
  image: plugins/npm
  settings:
    username: 
      from_secret: npm_username
    password: 
      from_secret: npm_password
    email:
      from_secret: npm_email


---
kind: secret
name: npm_username
data: k1OQhydeajopVgErsP0grDB7zYU9BYPzUmsjVK2K1vYQm9jrfsIsAXU=

--- 
kind: secret
name: npm_password
data: 0w8QcNB93Z8AD8yrES5KKFRqbkhSU7arwuR/c5ezeMvclv5+yNyEGprN67JcD9c=

--- 
kind: secret
name: npm_email
data: aU/9WfMB3vlzna6P/GJLuzgFYRX/PkdM7T8hevG8DDvGaBg3hPzstNSI8dkMf1izxky5PA==