kind: pipeline
type: docker
name: default

steps:
- name: install
  image: node:16
  commands:
    - npm install

- name: test
  image: node:16
  commands:
    - npm test

- name: build
  image: node:16
  commands:
    - npm run build
